// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/users/callback_data/datatype.proto

package callback_data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyboardType int32

const (
	KeyboardType_KT_NULL           KeyboardType = 0
	KeyboardType_KT_ACCOUNT        KeyboardType = 1
	KeyboardType_KT_TRANSACTIONS   KeyboardType = 2
	KeyboardType_KT_MULTI_OUT      KeyboardType = 3
	KeyboardType_KT_MULTI_OUT_SAME KeyboardType = 4
	KeyboardType_KT_BLOCKS         KeyboardType = 5
)

var KeyboardType_name = map[int32]string{
	0: "KT_NULL",
	1: "KT_ACCOUNT",
	2: "KT_TRANSACTIONS",
	3: "KT_MULTI_OUT",
	4: "KT_MULTI_OUT_SAME",
	5: "KT_BLOCKS",
}

var KeyboardType_value = map[string]int32{
	"KT_NULL":           0,
	"KT_ACCOUNT":        1,
	"KT_TRANSACTIONS":   2,
	"KT_MULTI_OUT":      3,
	"KT_MULTI_OUT_SAME": 4,
	"KT_BLOCKS":         5,
}

func (x KeyboardType) String() string {
	return proto.EnumName(KeyboardType_name, int32(x))
}

func (KeyboardType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c12396cafb085bf, []int{0}
}

type ActionType int32

const (
	ActionType_AT_NULL                 ActionType = 0
	ActionType_AT_REFRESH              ActionType = 1
	ActionType_AT_TRANSACTIONS         ActionType = 2
	ActionType_AT_MULTI_OUT            ActionType = 3
	ActionType_AT_MULTI_OUT_SAME       ActionType = 4
	ActionType_AT_BLOCKS               ActionType = 5
	ActionType_AT_BACK                 ActionType = 6
	ActionType_AT_NEXT                 ActionType = 7
	ActionType_AT_PREV                 ActionType = 8
	ActionType_AT_ENABLE_TX_NOTIFY     ActionType = 9
	ActionType_AT_DISABLE_TX_NOTIFY    ActionType = 10
	ActionType_AT_ENABLE_BLOCK_NOTIFY  ActionType = 11
	ActionType_AT_DISABLE_BLOCK_NOTIFY ActionType = 12
)

var ActionType_name = map[int32]string{
	0:  "AT_NULL",
	1:  "AT_REFRESH",
	2:  "AT_TRANSACTIONS",
	3:  "AT_MULTI_OUT",
	4:  "AT_MULTI_OUT_SAME",
	5:  "AT_BLOCKS",
	6:  "AT_BACK",
	7:  "AT_NEXT",
	8:  "AT_PREV",
	9:  "AT_ENABLE_TX_NOTIFY",
	10: "AT_DISABLE_TX_NOTIFY",
	11: "AT_ENABLE_BLOCK_NOTIFY",
	12: "AT_DISABLE_BLOCK_NOTIFY",
}

var ActionType_value = map[string]int32{
	"AT_NULL":                 0,
	"AT_REFRESH":              1,
	"AT_TRANSACTIONS":         2,
	"AT_MULTI_OUT":            3,
	"AT_MULTI_OUT_SAME":       4,
	"AT_BLOCKS":               5,
	"AT_BACK":                 6,
	"AT_NEXT":                 7,
	"AT_PREV":                 8,
	"AT_ENABLE_TX_NOTIFY":     9,
	"AT_DISABLE_TX_NOTIFY":    10,
	"AT_ENABLE_BLOCK_NOTIFY":  11,
	"AT_DISABLE_BLOCK_NOTIFY": 12,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c12396cafb085bf, []int{1}
}

type QueryDataType struct {
	MessageId            int64        `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Account              string       `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Keyboard             KeyboardType `protobuf:"varint,3,opt,name=keyboard,proto3,enum=callback_data.KeyboardType" json:"keyboard,omitempty"`
	Action               ActionType   `protobuf:"varint,4,opt,name=action,proto3,enum=callback_data.ActionType" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryDataType) Reset()         { *m = QueryDataType{} }
func (m *QueryDataType) String() string { return proto.CompactTextString(m) }
func (*QueryDataType) ProtoMessage()    {}
func (*QueryDataType) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c12396cafb085bf, []int{0}
}

func (m *QueryDataType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDataType.Unmarshal(m, b)
}
func (m *QueryDataType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDataType.Marshal(b, m, deterministic)
}
func (m *QueryDataType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDataType.Merge(m, src)
}
func (m *QueryDataType) XXX_Size() int {
	return xxx_messageInfo_QueryDataType.Size(m)
}
func (m *QueryDataType) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDataType.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDataType proto.InternalMessageInfo

func (m *QueryDataType) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *QueryDataType) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *QueryDataType) GetKeyboard() KeyboardType {
	if m != nil {
		return m.Keyboard
	}
	return KeyboardType_KT_NULL
}

func (m *QueryDataType) GetAction() ActionType {
	if m != nil {
		return m.Action
	}
	return ActionType_AT_NULL
}

func init() {
	proto.RegisterEnum("callback_data.KeyboardType", KeyboardType_name, KeyboardType_value)
	proto.RegisterEnum("callback_data.ActionType", ActionType_name, ActionType_value)
	proto.RegisterType((*QueryDataType)(nil), "callback_data.QueryDataType")
}

func init() {
	proto.RegisterFile("internal/users/callback_data/datatype.proto", fileDescriptor_2c12396cafb085bf)
}

var fileDescriptor_2c12396cafb085bf = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd2, 0x41, 0x8f, 0x93, 0x40,
	0x14, 0x07, 0x70, 0x69, 0xd7, 0x76, 0x79, 0xdb, 0xae, 0xe3, 0xac, 0xba, 0xe8, 0xc6, 0xa4, 0xf1,
	0xd4, 0xac, 0x49, 0x1b, 0xf5, 0xe0, 0x79, 0xca, 0xd2, 0x48, 0x86, 0x82, 0xc2, 0xc3, 0xd4, 0xd3,
	0x64, 0x0a, 0x13, 0xd3, 0xb4, 0x42, 0x03, 0x34, 0x91, 0x8f, 0xe0, 0xf7, 0xf1, 0x03, 0x9a, 0x22,
	0xb5, 0xb4, 0xf6, 0x42, 0xf2, 0xde, 0xff, 0xfd, 0xf9, 0x71, 0x00, 0xde, 0x2e, 0x93, 0x42, 0x65,
	0x89, 0x5c, 0x8f, 0xb7, 0xb9, 0xca, 0xf2, 0x71, 0x24, 0xd7, 0xeb, 0x85, 0x8c, 0x56, 0x22, 0x96,
	0x85, 0x1c, 0xef, 0x1e, 0x45, 0xb9, 0x51, 0xa3, 0x4d, 0x96, 0x16, 0x29, 0xed, 0x1f, 0xa5, 0x6f,
	0x7e, 0x6b, 0xd0, 0xff, 0xb2, 0x55, 0x59, 0xf9, 0x20, 0x0b, 0x89, 0xe5, 0x46, 0xd1, 0xd7, 0x00,
	0x3f, 0x54, 0x9e, 0xcb, 0xef, 0x4a, 0x2c, 0x63, 0x43, 0x1b, 0x68, 0xc3, 0xb6, 0xaf, 0xd7, 0x1b,
	0x3b, 0xa6, 0x06, 0x74, 0x65, 0x14, 0xa5, 0xdb, 0xa4, 0x30, 0x5a, 0x03, 0x6d, 0xa8, 0xfb, 0xfb,
	0x91, 0x7e, 0x84, 0xcb, 0x95, 0x2a, 0x17, 0xa9, 0xcc, 0x62, 0xa3, 0x3d, 0xd0, 0x86, 0xd7, 0xef,
	0xef, 0x46, 0x47, 0xd8, 0x88, 0xd7, 0xf1, 0xce, 0xf1, 0xff, 0x1d, 0xd3, 0x77, 0xd0, 0x91, 0x51,
	0xb1, 0x4c, 0x13, 0xe3, 0xa2, 0xaa, 0xbd, 0x3c, 0xa9, 0xb1, 0x2a, 0xac, 0x4a, 0xf5, 0xe1, 0xfd,
	0x4f, 0xe8, 0x35, 0x5f, 0x46, 0xaf, 0xa0, 0xcb, 0x51, 0xb8, 0xa1, 0xe3, 0x90, 0x47, 0xf4, 0x1a,
	0x80, 0xa3, 0x60, 0xa6, 0xe9, 0x85, 0x2e, 0x12, 0x8d, 0xde, 0xc0, 0x13, 0x8e, 0x02, 0x7d, 0xe6,
	0x06, 0xcc, 0x44, 0xdb, 0x73, 0x03, 0xd2, 0xa2, 0x04, 0x7a, 0x1c, 0xc5, 0x2c, 0x74, 0xd0, 0x16,
	0x5e, 0x88, 0xa4, 0x4d, 0x9f, 0xc3, 0xd3, 0xe6, 0x46, 0x04, 0x6c, 0x66, 0x91, 0x0b, 0xda, 0x07,
	0x9d, 0xa3, 0x98, 0x38, 0x9e, 0xc9, 0x03, 0xf2, 0xf8, 0xfe, 0x57, 0x0b, 0xe0, 0xf0, 0x41, 0x3b,
	0x98, 0x35, 0x61, 0x86, 0xc2, 0xb7, 0xa6, 0xbe, 0x15, 0x7c, 0xfa, 0x0b, 0xb3, 0x73, 0x30, 0xfb,
	0x0f, 0x66, 0xe7, 0x61, 0x76, 0x80, 0x6b, 0x69, 0xc2, 0x4c, 0x4e, 0x3a, 0x7b, 0xd6, 0x9a, 0x23,
	0xe9, 0xd6, 0xc3, 0x67, 0xdf, 0xfa, 0x4a, 0x2e, 0xe9, 0x2d, 0xdc, 0x30, 0x14, 0x96, 0xcb, 0x26,
	0x8e, 0x25, 0x70, 0x2e, 0x5c, 0x0f, 0xed, 0xe9, 0x37, 0xa2, 0x53, 0x03, 0x9e, 0x31, 0x14, 0x0f,
	0x76, 0x70, 0x92, 0x00, 0x7d, 0x05, 0x2f, 0x0e, 0x95, 0xca, 0xdb, 0x67, 0x57, 0xf4, 0x0e, 0x6e,
	0x1b, 0xad, 0xa3, 0xb0, 0xb7, 0xe8, 0x54, 0xbf, 0xd4, 0x87, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd9, 0x83, 0x55, 0x5b, 0x81, 0x02, 0x00, 0x00,
}
