// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/users/callbackdata/datatype.proto

package callbackdata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyboardType int32

const (
	KeyboardType_KT_NULL          KeyboardType = 0
	KeyboardType_KT_ACCOUNT       KeyboardType = 1
	KeyboardType_KT_PRICE_CHART   KeyboardType = 2
	KeyboardType_KT_NETWORK_CHART KeyboardType = 3
	KeyboardType_KT_CALC          KeyboardType = 4
	KeyboardType_KT_CONVERT       KeyboardType = 5
)

var KeyboardType_name = map[int32]string{
	0: "KT_NULL",
	1: "KT_ACCOUNT",
	2: "KT_PRICE_CHART",
	3: "KT_NETWORK_CHART",
	4: "KT_CALC",
	5: "KT_CONVERT",
}

var KeyboardType_value = map[string]int32{
	"KT_NULL":          0,
	"KT_ACCOUNT":       1,
	"KT_PRICE_CHART":   2,
	"KT_NETWORK_CHART": 3,
	"KT_CALC":          4,
	"KT_CONVERT":       5,
}

func (x KeyboardType) String() string {
	return proto.EnumName(KeyboardType_name, int32(x))
}

func (KeyboardType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18009145167ae7f1, []int{0}
}

type ActionType int32

const (
	ActionType_AT_NULL                           ActionType = 0
	ActionType_AT_REFRESH                        ActionType = 1
	ActionType_AT_PAYMENTS                       ActionType = 2
	ActionType_AT_MULTI_OUT                      ActionType = 3
	ActionType_AT_MULTI_OUT_SAME                 ActionType = 4
	ActionType_AT_BLOCKS                         ActionType = 5
	ActionType_AT_BACK                           ActionType = 6
	ActionType_AT_NEXT                           ActionType = 7
	ActionType_AT_PREV                           ActionType = 8
	ActionType_AT_ENABLE_INCOME_TX_NOTIFY        ActionType = 9
	ActionType_AT_DISABLE_INCOME_TX_NOTIFY       ActionType = 10
	ActionType_AT_ENABLE_BLOCK_NOTIFY            ActionType = 11
	ActionType_AT_DISABLE_BLOCK_NOTIFY           ActionType = 12
	ActionType_AT_ENABLE_OUTGO_TX_NOTIFY         ActionType = 13
	ActionType_AT_DISABLE_OUTGO_TX_NOTIFY        ActionType = 14
	ActionType_AT_PRICE_CHART_1_DAY              ActionType = 15
	ActionType_AT_PRICE_CHART_1_WEEK             ActionType = 16
	ActionType_AT_PRICE_CHART_1_MONTH            ActionType = 17
	ActionType_AT_PRICE_CHART_ALL                ActionType = 18
	ActionType_AT_NETWORK_CHART_1_MONTH          ActionType = 19
	ActionType_AT_NETWORK_CHART_ALL              ActionType = 20
	ActionType_AT_OTHER_TXS                      ActionType = 21
	ActionType_AT_ENABLE_OTHER_TX_NOTIFICATIONS  ActionType = 22
	ActionType_AT_DISABLE_OTHER_TX_NOTIFICATIONS ActionType = 23
	ActionType_AT_CALC_TIB                       ActionType = 24
	ActionType_AT_CALC_TB                        ActionType = 25
	ActionType_AT_CONVERT_SIGNA                  ActionType = 26
	ActionType_AT_CONVERT_USD                    ActionType = 27
	ActionType_AT_CONVERT_BTC                    ActionType = 28
)

var ActionType_name = map[int32]string{
	0:  "AT_NULL",
	1:  "AT_REFRESH",
	2:  "AT_PAYMENTS",
	3:  "AT_MULTI_OUT",
	4:  "AT_MULTI_OUT_SAME",
	5:  "AT_BLOCKS",
	6:  "AT_BACK",
	7:  "AT_NEXT",
	8:  "AT_PREV",
	9:  "AT_ENABLE_INCOME_TX_NOTIFY",
	10: "AT_DISABLE_INCOME_TX_NOTIFY",
	11: "AT_ENABLE_BLOCK_NOTIFY",
	12: "AT_DISABLE_BLOCK_NOTIFY",
	13: "AT_ENABLE_OUTGO_TX_NOTIFY",
	14: "AT_DISABLE_OUTGO_TX_NOTIFY",
	15: "AT_PRICE_CHART_1_DAY",
	16: "AT_PRICE_CHART_1_WEEK",
	17: "AT_PRICE_CHART_1_MONTH",
	18: "AT_PRICE_CHART_ALL",
	19: "AT_NETWORK_CHART_1_MONTH",
	20: "AT_NETWORK_CHART_ALL",
	21: "AT_OTHER_TXS",
	22: "AT_ENABLE_OTHER_TX_NOTIFICATIONS",
	23: "AT_DISABLE_OTHER_TX_NOTIFICATIONS",
	24: "AT_CALC_TIB",
	25: "AT_CALC_TB",
	26: "AT_CONVERT_SIGNA",
	27: "AT_CONVERT_USD",
	28: "AT_CONVERT_BTC",
}

var ActionType_value = map[string]int32{
	"AT_NULL":                           0,
	"AT_REFRESH":                        1,
	"AT_PAYMENTS":                       2,
	"AT_MULTI_OUT":                      3,
	"AT_MULTI_OUT_SAME":                 4,
	"AT_BLOCKS":                         5,
	"AT_BACK":                           6,
	"AT_NEXT":                           7,
	"AT_PREV":                           8,
	"AT_ENABLE_INCOME_TX_NOTIFY":        9,
	"AT_DISABLE_INCOME_TX_NOTIFY":       10,
	"AT_ENABLE_BLOCK_NOTIFY":            11,
	"AT_DISABLE_BLOCK_NOTIFY":           12,
	"AT_ENABLE_OUTGO_TX_NOTIFY":         13,
	"AT_DISABLE_OUTGO_TX_NOTIFY":        14,
	"AT_PRICE_CHART_1_DAY":              15,
	"AT_PRICE_CHART_1_WEEK":             16,
	"AT_PRICE_CHART_1_MONTH":            17,
	"AT_PRICE_CHART_ALL":                18,
	"AT_NETWORK_CHART_1_MONTH":          19,
	"AT_NETWORK_CHART_ALL":              20,
	"AT_OTHER_TXS":                      21,
	"AT_ENABLE_OTHER_TX_NOTIFICATIONS":  22,
	"AT_DISABLE_OTHER_TX_NOTIFICATIONS": 23,
	"AT_CALC_TIB":                       24,
	"AT_CALC_TB":                        25,
	"AT_CONVERT_SIGNA":                  26,
	"AT_CONVERT_USD":                    27,
	"AT_CONVERT_BTC":                    28,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18009145167ae7f1, []int{1}
}

type QueryDataType struct {
	MessageId            int64        `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Account              string       `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Keyboard             KeyboardType `protobuf:"varint,3,opt,name=keyboard,proto3,enum=callbackdata.KeyboardType" json:"keyboard,omitempty"`
	Action               ActionType   `protobuf:"varint,4,opt,name=action,proto3,enum=callbackdata.ActionType" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryDataType) Reset()         { *m = QueryDataType{} }
func (m *QueryDataType) String() string { return proto.CompactTextString(m) }
func (*QueryDataType) ProtoMessage()    {}
func (*QueryDataType) Descriptor() ([]byte, []int) {
	return fileDescriptor_18009145167ae7f1, []int{0}
}

func (m *QueryDataType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDataType.Unmarshal(m, b)
}
func (m *QueryDataType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDataType.Marshal(b, m, deterministic)
}
func (m *QueryDataType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDataType.Merge(m, src)
}
func (m *QueryDataType) XXX_Size() int {
	return xxx_messageInfo_QueryDataType.Size(m)
}
func (m *QueryDataType) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDataType.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDataType proto.InternalMessageInfo

func (m *QueryDataType) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *QueryDataType) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *QueryDataType) GetKeyboard() KeyboardType {
	if m != nil {
		return m.Keyboard
	}
	return KeyboardType_KT_NULL
}

func (m *QueryDataType) GetAction() ActionType {
	if m != nil {
		return m.Action
	}
	return ActionType_AT_NULL
}

func init() {
	proto.RegisterEnum("callbackdata.KeyboardType", KeyboardType_name, KeyboardType_value)
	proto.RegisterEnum("callbackdata.ActionType", ActionType_name, ActionType_value)
	proto.RegisterType((*QueryDataType)(nil), "callbackdata.QueryDataType")
}

func init() {
	proto.RegisterFile("internal/users/callbackdata/datatype.proto", fileDescriptor_18009145167ae7f1)
}

var fileDescriptor_18009145167ae7f1 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdb, 0x4e, 0xdb, 0x40,
	0x10, 0xad, 0xb9, 0x67, 0x08, 0x61, 0x98, 0x72, 0x31, 0x01, 0xda, 0xb4, 0x6a, 0x25, 0xc4, 0x03,
	0xf4, 0x22, 0xf5, 0x7d, 0xb3, 0x59, 0x88, 0x65, 0xc7, 0x4b, 0xed, 0x09, 0x97, 0xa7, 0x95, 0x49,
	0xac, 0x0a, 0x41, 0x13, 0x94, 0x98, 0x87, 0x7c, 0x56, 0xfb, 0x85, 0x95, 0xc3, 0x06, 0x9c, 0x94,
	0x17, 0x4b, 0x7b, 0xce, 0x9c, 0x39, 0x33, 0x9a, 0x63, 0x38, 0xba, 0xed, 0x65, 0xe9, 0xa0, 0x97,
	0xdc, 0x9f, 0x3c, 0x0e, 0xd3, 0xc1, 0xf0, 0xa4, 0x93, 0xdc, 0xdf, 0xdf, 0x24, 0x9d, 0xbb, 0x6e,
	0x92, 0x25, 0x27, 0xf9, 0x27, 0x1b, 0x3d, 0xa4, 0xc7, 0x0f, 0x83, 0x7e, 0xd6, 0xa7, 0x72, 0x91,
	0xfc, 0xf8, 0xd7, 0x81, 0xb5, 0x9f, 0x8f, 0xe9, 0x60, 0xd4, 0x48, 0xb2, 0x84, 0x47, 0x0f, 0x29,
	0x1d, 0x00, 0xfc, 0x4e, 0x87, 0xc3, 0xe4, 0x57, 0x6a, 0x6e, 0xbb, 0xae, 0x53, 0x73, 0x0e, 0xe7,
	0xa3, 0x92, 0x45, 0xbc, 0x2e, 0xb9, 0xb0, 0x9c, 0x74, 0x3a, 0xfd, 0xc7, 0x5e, 0xe6, 0xce, 0xd5,
	0x9c, 0xc3, 0x52, 0x34, 0x79, 0xd2, 0x0f, 0x58, 0xb9, 0x4b, 0x47, 0x37, 0xfd, 0x64, 0xd0, 0x75,
	0xe7, 0x6b, 0xce, 0x61, 0xe5, 0x5b, 0xf5, 0xb8, 0xe8, 0x75, 0xec, 0x5b, 0x36, 0xb7, 0x89, 0x9e,
	0x6b, 0xe9, 0x0b, 0x2c, 0x25, 0x9d, 0xec, 0xb6, 0xdf, 0x73, 0x17, 0xc6, 0x2a, 0x77, 0x5a, 0x25,
	0xc6, 0xdc, 0x58, 0x63, 0xeb, 0x8e, 0x06, 0x50, 0x2e, 0xf6, 0xa2, 0x55, 0x58, 0xf6, 0xd9, 0x84,
	0xed, 0x20, 0xc0, 0x37, 0x54, 0x01, 0xf0, 0xd9, 0x08, 0x29, 0x75, 0x3b, 0x64, 0x74, 0x88, 0xa0,
	0xe2, 0xb3, 0x39, 0x8f, 0x3c, 0xa9, 0x8c, 0x6c, 0x8a, 0x88, 0x71, 0x8e, 0x36, 0x01, 0x73, 0x81,
	0xe2, 0x4b, 0x1d, 0xf9, 0x16, 0x9d, 0xb7, 0x6d, 0xa4, 0x08, 0x24, 0x2e, 0xd8, 0x36, 0x52, 0x87,
	0x17, 0x2a, 0x62, 0x5c, 0x3c, 0xfa, 0xb3, 0x08, 0xf0, 0x32, 0x4a, 0x5e, 0x2b, 0x8a, 0x96, 0x82,
	0x4d, 0xa4, 0x4e, 0x23, 0x15, 0x37, 0xd1, 0xa1, 0x75, 0x58, 0x15, 0x6c, 0xce, 0xc5, 0x75, 0x4b,
	0x85, 0x1c, 0xe3, 0x1c, 0x21, 0x94, 0x05, 0x9b, 0x56, 0x3b, 0x60, 0xcf, 0xe8, 0x76, 0xee, 0xb5,
	0x05, 0x1b, 0x45, 0xc4, 0xc4, 0xa2, 0xa5, 0x70, 0x81, 0xd6, 0xa0, 0x24, 0xd8, 0xd4, 0x03, 0x2d,
	0xfd, 0x18, 0x17, 0xad, 0x4b, 0x5d, 0x48, 0x1f, 0x97, 0x26, 0x96, 0xea, 0x8a, 0x71, 0xd9, 0x3e,
	0xce, 0x23, 0x75, 0x81, 0x2b, 0xf4, 0x0e, 0xaa, 0x82, 0x8d, 0x0a, 0x45, 0x3d, 0x50, 0xc6, 0x0b,
	0xa5, 0x6e, 0x29, 0xc3, 0x57, 0x26, 0xd4, 0xec, 0x9d, 0x5e, 0x63, 0x89, 0xde, 0xc3, 0x9e, 0x60,
	0xd3, 0xf0, 0xe2, 0xd7, 0x0b, 0x80, 0xaa, 0xb0, 0xfd, 0xd2, 0x60, 0xec, 0x3e, 0xe1, 0x56, 0x69,
	0x0f, 0x76, 0x0a, 0xe2, 0x29, 0xb2, 0x4c, 0x07, 0xb0, 0xfb, 0x22, 0xd4, 0x6d, 0x3e, 0xd3, 0x85,
	0xbe, 0x6b, 0x76, 0xb0, 0x89, 0x76, 0x96, 0xaf, 0x90, 0x0b, 0x9b, 0x62, 0xea, 0x36, 0xe6, 0xab,
	0x69, 0x88, 0x6b, 0x5c, 0xa7, 0x5d, 0xd8, 0xfa, 0x8f, 0xb9, 0x54, 0xca, 0x47, 0xb4, 0xc3, 0x4e,
	0x53, 0x2d, 0x1d, 0x72, 0x13, 0x37, 0x68, 0x1b, 0x68, 0x86, 0x13, 0x41, 0x80, 0x44, 0xfb, 0xe0,
	0x8a, 0x99, 0x83, 0x3f, 0xab, 0xde, 0xda, 0x31, 0xa6, 0xd9, 0x5c, 0xb7, 0x69, 0x0f, 0xa7, 0xb9,
	0xa9, 0x22, 0xc3, 0x57, 0x31, 0x6e, 0xd1, 0x27, 0xa8, 0x15, 0x36, 0xb6, 0xc4, 0xd3, 0x46, 0x9e,
	0x14, 0xec, 0xe9, 0x30, 0xc6, 0x6d, 0xfa, 0x0c, 0x1f, 0x8a, 0x8b, 0xbf, 0x5e, 0xb6, 0x63, 0x83,
	0x92, 0x27, 0xce, 0xb0, 0x57, 0x47, 0xd7, 0x26, 0xe9, 0x09, 0xa8, 0xe3, 0x6e, 0x1e, 0x54, 0xf1,
	0x9c, 0x42, 0x13, 0x7b, 0x67, 0xa1, 0xc0, 0x6a, 0x1e, 0xe9, 0x02, 0xda, 0x8e, 0x1b, 0xb8, 0x37,
	0x83, 0xd5, 0x59, 0xe2, 0xfe, 0xcd, 0xd2, 0xf8, 0x8f, 0xff, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0xe9, 0xe2, 0x1e, 0x0c, 0x1f, 0x04, 0x00, 0x00,
}
